/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaymentsIndexRouteImport } from './routes/payments/index'
import { Route as PaymentsYearIndexRouteImport } from './routes/payments/$year/index'
import { Route as PaymentsYearMonthRouteImport } from './routes/payments/$year/$month'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsYearIndexRoute = PaymentsYearIndexRouteImport.update({
  id: '/payments/$year/',
  path: '/payments/$year/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsYearMonthRoute = PaymentsYearMonthRouteImport.update({
  id: '/payments/$year/$month',
  path: '/payments/$year/$month',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/payments': typeof PaymentsIndexRoute
  '/payments/$year/$month': typeof PaymentsYearMonthRoute
  '/payments/$year': typeof PaymentsYearIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/payments': typeof PaymentsIndexRoute
  '/payments/$year/$month': typeof PaymentsYearMonthRoute
  '/payments/$year': typeof PaymentsYearIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/payments/': typeof PaymentsIndexRoute
  '/payments/$year/$month': typeof PaymentsYearMonthRoute
  '/payments/$year/': typeof PaymentsYearIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/payments'
    | '/payments/$year/$month'
    | '/payments/$year'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/payments'
    | '/payments/$year/$month'
    | '/payments/$year'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/payments/'
    | '/payments/$year/$month'
    | '/payments/$year/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PaymentsIndexRoute: typeof PaymentsIndexRoute
  PaymentsYearMonthRoute: typeof PaymentsYearMonthRoute
  PaymentsYearIndexRoute: typeof PaymentsYearIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/': {
      id: '/payments/'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/$year/': {
      id: '/payments/$year/'
      path: '/payments/$year'
      fullPath: '/payments/$year'
      preLoaderRoute: typeof PaymentsYearIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/$year/$month': {
      id: '/payments/$year/$month'
      path: '/payments/$year/$month'
      fullPath: '/payments/$year/$month'
      preLoaderRoute: typeof PaymentsYearMonthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
  PaymentsYearMonthRoute: PaymentsYearMonthRoute,
  PaymentsYearIndexRoute: PaymentsYearIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
